#cloud-config
manage_etc_hosts: true
runcmd:
- echo prueba > /root/fichero.txt
#- sed -i 's/"1"/"0"/g' /etc/apt/apt.conf.d/20auto-upgrades
# Mirar configuracion isc
- echo "INTERFACES='ens3'" > /etc/default/isc-dhcp-server 
- echo "ddns-update-style none;" > /etc/dhcp/dhcpd.conf
- echo "default-lease-time 604800;" >> /etc/dhcp/dhcpd.conf
- echo "max-lease-time 604800;" >> /etc/dhcp/dhcpd.conf
- echo "subnet 10.0.0.0 netmask 255.255.255.0 {}" >> /etc/dhcp/dhcpd.conf
- echo "subnet 10.1.10.0 netmask 255.255.255.0 {">> /etc/dhcp/dhcpd.conf
- echo "  range 10.1.10.10 10.1.10.30;">> /etc/dhcp/dhcpd.conf
- echo "  option routers 10.1.10.254;">> /etc/dhcp/dhcpd.conf
- echo "  option domain-name-servers 8.8.8.8;}">> /etc/dhcp/dhcpd.conf
- service isc-dhcp-server start
- echo 1 > /proc/sys/net/ipv4/ip_forward


#Hay un error con la ruta hacia la maquina de cloud y hay que poner el siguiente paso y el dev 

